'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminHomePage_EditStudentProfile

    '''<summary>
    '''SelectedAccountsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedAccountsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelectedAccountsListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedAccountsListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''SetEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NoChangeEmailRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoChangeEmailRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SetManuallyEmailRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetManuallyEmailRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ManualSetEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManualSetEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManualSetEmailField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManualSetEmailField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ErrorInEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SetPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NoChangePasswordRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoChangePasswordRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''SetManuallyPasswordRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SetManuallyPasswordRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''AutoGeneratePasswordRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoGeneratePasswordRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ManualSetPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManualSetPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ManualSetPasswordField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ManualSetPasswordField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmPasswordField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmPasswordField As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ErrorInPasswordLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorInPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmChangesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmChangesButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button
End Class
