'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StudentHomePage_GradesContent

    '''<summary>
    '''StudentNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''YearDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CampusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CampusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SchoolYearLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SchoolYearLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TermLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TermLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''StudentGradeInfoGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentGradeInfoGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DownloadGradesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadGradesButton As Global.System.Web.UI.WebControls.LinkButton
End Class
